sudo: required
dist: trusty
language: node_js
node_js:
- '8'
before_deploy: npm run build
deploy:
  provider: npm
  email: esurendhar95@gmail.com
  api_key:
    secure: h0rSc8R/gWw7xt3BtvxEIAc0yCXtUuwoMWe2kyFdBa3MtqgNKVM/q9UPvPu0IwnIdGUVEYqokaQU4/41ih5tjwyRo8Wsmz18sD/qGYH1rTCg1QTEom/fJdjMT8yDWWSXanulRyv09DFZhySfPVtzVQQcKTP3hZ8NKtBx48BUf19yuShOibFjWVuGYf1IJ1UlagtIdV1USB3c4lS9GbGKcv6fzyLekxRF5YW48AvqFS6EddPOEj/z9rWyMb9kyGsG+earmEpaIU6cobMTzosIbG0C58lNBKi552m8wGkaGgsRqk6kREOS0HdHFVkypHjddyOX0UIiq0aiOmF7UHo8YKaSjDbZqfl5tkxXHHKlRmCX4V9s64QzsxjwW+2TF2u50uuA12wFe7wHyctOJoZGPs8ILfmNaSVjYXBPkDpG1bpyk9csmkGs00o/fn2uBoZrwwRiPmTB0FPQDcuy6jW1RmSfqfgJv6XPetwFuc+Ry2eb+4/GocOJ9Ee13Ei83akZJutSOQjQfuyiqdMTu0Q1qFV0k+ChO6jWmUYsf/sOg353hUNmI8XP3ciUJE17ifhK7HlOSkzcu32bL6qc3nVft2GvQxejOwIGq2NldmHVQ9THwZ5BZ20++g0DVhXIxt7HuF70tZ3VE6m/CR0SoPehLrxyxZNe1YMUEoET3UDyITY=
  on:
    repo: commutatus/cm-page-builder
    branch: master
