deploy:
  provider: npm
  email: vivsri95@gmail.com
  api_key:
    secure: h1zaam6IStiaKbW7vWoxN/nfHZnUjUP2h0lLwO78gDFKWV1e47ozV+EvSXPwIeLa5g3vcu7RpHoOYfAreeEBDOcE9TZ5HREeE8lMbRGkpVtKkm4A/jOH7MvTS3CDvLF4QsRsFwg1S/bOBHQS9r1EnenL6McI0/HkijnO8NJgieallguZDA3/+QsNKykhLDgNJ0yDbzIfRGKMiKWGaA3vjUB33nKsP8HIDB3+/Lhj3beBb+yY1NGDPbCV7USFanx/Y7HxohCEQ7wONhrX5gsY/DpK7n2gM/CK5gbIv63vW2eBm6I47Y7W6fcTdTX4+SfBwbjHD4hYbfRZoEbEZzxTZ989IVqs+cECMWOiYnpAAs+RiPHN6Cur7pgP7b3B182BviwQVxshPQDDHFEDwPEAgVCT/LfghLRKnsHVu9qfJTdYkkcAYmGIWcKbjExnXjowDFjxrX8xOugqvOm4GsW/YaKuKoYLQcSSDbycmpZ5O55ovkeCvjGA7hROGZ6Tuaf4uGSnxE80b/UX7tlVpo+HzTIs6eqZ4exCKJIb+vhhJT0RYF6fTT+C56OSnOWI0v9qbLIHk+11Z2Obq62H1Y0vA08cDFMRL2oAsy3Du8ikLDCWblpOonZhPkDHmWASdsNcuETCdionNiFGju1SBZhPGwHIpYiqvm4pUA0bDVs2yhU=
  on:
    repo: commutatus/cm-page-builder
